// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD3yNcTsB_nirqh1ILJefqDKlwQlSq4cI',
    appId: '1:1062689125653:web:4a8ea7cb2d40c6046ca51c',
    messagingSenderId: '1062689125653',
    projectId: 'practice1-7890a',
    authDomain: 'practice1-7890a.firebaseapp.com',
    storageBucket: 'practice1-7890a.appspot.com',
    measurementId: 'G-5XL86PRGDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqQy2MahqOeqpVv9qHzFwz1D5Am7u1_LE',
    appId: '1:1062689125653:android:fb4542c1024c448c6ca51c',
    messagingSenderId: '1062689125653',
    projectId: 'practice1-7890a',
    storageBucket: 'practice1-7890a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm7BtNjoTu5pm4HsQw3zW-8CmA91-RWJw',
    appId: '1:1062689125653:ios:b9512c670d4badc56ca51c',
    messagingSenderId: '1062689125653',
    projectId: 'practice1-7890a',
    storageBucket: 'practice1-7890a.appspot.com',
    iosBundleId: 'com.example.practice1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm7BtNjoTu5pm4HsQw3zW-8CmA91-RWJw',
    appId: '1:1062689125653:ios:33e5270f6a4afbf76ca51c',
    messagingSenderId: '1062689125653',
    projectId: 'practice1-7890a',
    storageBucket: 'practice1-7890a.appspot.com',
    iosBundleId: 'com.example.practice1.RunnerTests',
  );
}
